# Form implementation generated from reading ui file 'D:\PythonProject\testck\ui\PaymentWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PaymentWindow(object):
    def setupUi(self, PaymentWindow):
        PaymentWindow.setObjectName("PaymentWindow")
        PaymentWindow.resize(520, 727)
        PaymentWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=PaymentWindow)
        self.centralwidget.setStyleSheet("/* Ép màu cho centralwidget và tất cả các con bên trong */\n"
"#centralwidget {\n"
"    background-color: #FFFFFF; /* Nền trắng */\n"
"    color: #000000;            /* Chữ đen */\n"
"}\n"
"\n"
"/* Đảm bảo các Label không bị Theme hệ thống ghi đè màu trắng */\n"
"QLabel {\n"
"    color: #000000;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setStyleSheet("font-size: 22px; font-weight: bold; color: #4A90E2; font-family: \'Georgia\';")
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.frameTotal = QtWidgets.QFrame(parent=self.centralwidget)
        self.frameTotal.setStyleSheet("background-color: #F0F7FF; border-radius: 15px; border: 1px solid #CFE4FF;")
        self.frameTotal.setObjectName("frameTotal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameTotal)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frameTotal)
        self.label_2.setStyleSheet("color: rgb(15, 15, 15);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lblTotalValue = QtWidgets.QLabel(parent=self.frameTotal)
        self.lblTotalValue.setStyleSheet("font-size: 32px; font-weight: bold; color: #0D3B66;")
        self.lblTotalValue.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTotalValue.setObjectName("lblTotalValue")
        self.verticalLayout_2.addWidget(self.lblTotalValue)
        self.verticalLayout.addWidget(self.frameTotal)
        self.labelQR = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelQR.setMinimumSize(QtCore.QSize(350, 350))
        self.labelQR.setMaximumSize(QtCore.QSize(350, 350))
        self.labelQR.setStyleSheet("border: 2px dashed #AFCBF3; border-radius: 10px;")
        self.labelQR.setText("")
        self.labelQR.setPixmap(QtGui.QPixmap("D:\\PythonProject\\testck\\ui\\../ima/download.png"))
        self.labelQR.setScaledContents(True)
        self.labelQR.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelQR.setObjectName("labelQR")
        self.verticalLayout.addWidget(self.labelQR, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color: rgb(9, 9, 9);\n"
"")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.btnConfirm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnConfirm.setMinimumSize(QtCore.QSize(0, 50))
        self.btnConfirm.setStyleSheet("QPushButton {\n"
"    background-color: #AFCBF3;\n"
"    color: #0D3B66;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border-radius: 15px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF;\n"
"}")
        self.btnConfirm.setObjectName("btnConfirm")
        self.verticalLayout.addWidget(self.btnConfirm)
        PaymentWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PaymentWindow)
        QtCore.QMetaObject.connectSlotsByName(PaymentWindow)

    def retranslateUi(self, PaymentWindow):
        _translate = QtCore.QCoreApplication.translate
        PaymentWindow.setWindowTitle(_translate("PaymentWindow", "Secure Payment"))
        self.labelTitle.setText(_translate("PaymentWindow", "PAYMENT CHECKOUT"))
        self.label_2.setText(_translate("PaymentWindow", "Total Amount Due:"))
        self.lblTotalValue.setText(_translate("PaymentWindow", "0.00$"))
        self.checkBox.setText(_translate("PaymentWindow", "Cash payment"))
        self.btnConfirm.setText(_translate("PaymentWindow", "DONE"))
