# Form implementation generated from reading ui file 'D:\PythonProject\nail_shop\ui\FeedbackWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RatingUI(object):
    def setupUi(self, RatingUI):
        RatingUI.setObjectName("RatingUI")
        RatingUI.resize(450, 460)
        RatingUI.setStyleSheet("QWidget { background-color: #e6f4fa; color: #000000; font-family: \'Georgia\'; } QFrame { background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #ffffff, stop:0.5 #e6f4fa, stop:1 #d4edf7); border-radius: 20px; } QLabel { background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(255,255,255,220), stop:1 rgba(255,255,255,150)); border-radius: 15px; padding: 8px 15px; border: 1px solid rgba(255,255,255,180); }")
        self.verticalLayout = QtWidgets.QVBoxLayout(RatingUI)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblInstruction = QtWidgets.QLabel(parent=RatingUI)
        self.lblInstruction.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblInstruction.setStyleSheet("font-size: 18px; font-weight: bold; color: rgb(190,215,226);")
        self.lblInstruction.setObjectName("lblInstruction")
        self.verticalLayout.addWidget(self.lblInstruction)
        self.starLayout = QtWidgets.QHBoxLayout()
        self.starLayout.setObjectName("starLayout")
        self.star_1 = QtWidgets.QPushButton(parent=RatingUI)
        self.star_1.setMinimumSize(QtCore.QSize(50, 50))
        self.star_1.setStyleSheet("QPushButton { background: transparent; color: #333; font-size: 35px; border: none; } QPushButton:hover { color: gold; }")
        self.star_1.setObjectName("star_1")
        self.starLayout.addWidget(self.star_1)
        self.star_2 = QtWidgets.QPushButton(parent=RatingUI)
        self.star_2.setMinimumSize(QtCore.QSize(50, 50))
        self.star_2.setStyleSheet("QPushButton { background: transparent; color: #333; font-size: 35px; border: none; }")
        self.star_2.setObjectName("star_2")
        self.starLayout.addWidget(self.star_2)
        self.star_3 = QtWidgets.QPushButton(parent=RatingUI)
        self.star_3.setMinimumSize(QtCore.QSize(50, 50))
        self.star_3.setStyleSheet("QPushButton { background: transparent; color: #333; font-size: 35px; border: none; }")
        self.star_3.setObjectName("star_3")
        self.starLayout.addWidget(self.star_3)
        self.star_4 = QtWidgets.QPushButton(parent=RatingUI)
        self.star_4.setMinimumSize(QtCore.QSize(50, 50))
        self.star_4.setStyleSheet("QPushButton { background: transparent; color: #333; font-size: 35px; border: none; }")
        self.star_4.setObjectName("star_4")
        self.starLayout.addWidget(self.star_4)
        self.star_5 = QtWidgets.QPushButton(parent=RatingUI)
        self.star_5.setMinimumSize(QtCore.QSize(50, 50))
        self.star_5.setStyleSheet("QPushButton { background: transparent; color: #333; font-size: 35px; border: none; }")
        self.star_5.setObjectName("star_5")
        self.starLayout.addWidget(self.star_5)
        self.verticalLayout.addLayout(self.starLayout)
        self.lblFeedback = QtWidgets.QLabel(parent=RatingUI)
        self.lblFeedback.setStyleSheet("QLabel { background-color: transparent; }")
        self.lblFeedback.setObjectName("lblFeedback")
        self.verticalLayout.addWidget(self.lblFeedback)
        self.lineEditFeedback = QtWidgets.QLineEdit(parent=RatingUI)
        self.lineEditFeedback.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEditFeedback.setStyleSheet("QLineEdit { background-color: rgb(208,236,250); color: rgb(15,15,15); border: 2px solid #AFCBF3; border-radius: 20px; padding: 6px 10px; }")
        self.lineEditFeedback.setObjectName("lineEditFeedback")
        self.verticalLayout.addWidget(self.lineEditFeedback)
        self.btnSubmit = QtWidgets.QPushButton(parent=RatingUI)
        self.btnSubmit.setMinimumSize(QtCore.QSize(0, 45))
        self.btnSubmit.setStyleSheet("QPushButton { background-color: rgb(208,236,250); color: #0D3B66; font-weight: bold; font-size: 15px; border: none; border-radius: 15px; padding: 8px 15px; } QPushButton:hover { background-color: rgb(208,236,250); } QPushButton:pressed { background-color: #8FB6F5; }")
        self.btnSubmit.setObjectName("btnSubmit")
        self.verticalLayout.addWidget(self.btnSubmit)

        self.retranslateUi(RatingUI)
        QtCore.QMetaObject.connectSlotsByName(RatingUI)

    def retranslateUi(self, RatingUI):
        _translate = QtCore.QCoreApplication.translate
        RatingUI.setWindowTitle(_translate("RatingUI", "Rate Our Service"))
        self.lblInstruction.setText(_translate("RatingUI", "How was your experience today?"))
        self.star_1.setText(_translate("RatingUI", "★"))
        self.star_2.setText(_translate("RatingUI", "★"))
        self.star_3.setText(_translate("RatingUI", "★"))
        self.star_4.setText(_translate("RatingUI", "★"))
        self.star_5.setText(_translate("RatingUI", "★"))
        self.lblFeedback.setText(_translate("RatingUI", "Leave a feedback for us:"))
        self.lineEditFeedback.setPlaceholderText(_translate("RatingUI", "Your thoughts..."))
        self.btnSubmit.setText(_translate("RatingUI", "SEND"))
