# Form implementation generated from reading ui file 'D:\UEL\PythonProject\CustomerManagement\ui\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1407, 1007)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(234, 242, 251);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.headerWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.headerWidget.setMaximumSize(QtCore.QSize(16777215, 70))
        self.headerWidget.setStyleSheet("color: white;\n"
"font-size: 14px;\n"
"background-color: rgb(167, 212, 238);\n"
" border-radius: 20px;  /* Bo góc 15px */\n"
"   \n"
"")
        self.headerWidget.setObjectName("headerWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.headerWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(parent=self.headerWidget)
        self.label.setStyleSheet("  font-size: 30px; /* Cỡ chữ lớn */\n"
"    font-weight: bold; /* Chữ đậm */\n"
"    font-family: \"Georgia\", serif; /* Font chữ sang trọng */\n"
"    color: white;\n"
"    text-align: center; \n"
"\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.label_10 = QtWidgets.QLabel(parent=self.headerWidget)
        self.label_10.setStyleSheet("")
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.verticalLayout_4.addWidget(self.headerWidget)
        self.navBar = QtWidgets.QWidget(parent=self.centralwidget)
        self.navBar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.navBar.setStyleSheet("background-color: white;\n"
"border-bottom: 1px solid #ddd;\n"
"border-bottom-color: rgb(0, 0, 255);\n"
"border: 1px solid rgb(67, 139, 196);\n"
"color: rgb(0, 0, 127);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"\n"
"")
        self.navBar.setObjectName("navBar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.navBar)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Spring = QtWidgets.QPushButton(parent=self.navBar)
        self.Spring.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.Spring.setStyleSheet("QPushButton {\n"
"    background: transparent; /* Nền trong suốt để lộ màu trắng của NavBar */\n"
"    border: none; /* Không có khung viền */\n"
"    font-size: 14px;\n"
"    font-family: \"Georgia\";\n"
"    color: #4A90E2; /* Chuyển sang màu xanh dương để hợp với tông #CFE4FF */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #0D3B66; /* Màu xanh đậm hơn khi di chuột qua để tạo điểm nhấn */\n"
"    text-decoration: underline; /* Hiện gạch chân khi hover giống như một liên kết */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #CFE4FF; /* Màu xanh nhạt xuất hiện khi nhấn vào */\n"
"}")
        self.Spring.setObjectName("Spring")
        self.horizontalLayout.addWidget(self.Spring)
        self.Summer = QtWidgets.QPushButton(parent=self.navBar)
        self.Summer.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.Summer.setStyleSheet("QPushButton {\n"
"    background: transparent; /* Nền trong suốt để lộ màu trắng của NavBar */\n"
"    border: none; /* Không có khung viền */\n"
"    font-size: 14px;\n"
"    font-family: \"Georgia\";\n"
"    color: #4A90E2; /* Chuyển sang màu xanh dương để hợp với tông #CFE4FF */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #0D3B66; /* Màu xanh đậm hơn khi di chuột qua để tạo điểm nhấn */\n"
"    text-decoration: underline; /* Hiện gạch chân khi hover giống như một liên kết */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #CFE4FF; /* Màu xanh nhạt xuất hiện khi nhấn vào */\n"
"}")
        self.Summer.setObjectName("Summer")
        self.horizontalLayout.addWidget(self.Summer)
        self.Autumn = QtWidgets.QPushButton(parent=self.navBar)
        self.Autumn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.Autumn.setStyleSheet("QPushButton {\n"
"    background: transparent; /* Nền trong suốt để lộ màu trắng của NavBar */\n"
"    border: none; /* Không có khung viền */\n"
"    font-size: 14px;\n"
"    font-family: \"Georgia\";\n"
"    color: #4A90E2; /* Chuyển sang màu xanh dương để hợp với tông #CFE4FF */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #0D3B66; /* Màu xanh đậm hơn khi di chuột qua để tạo điểm nhấn */\n"
"    text-decoration: underline; /* Hiện gạch chân khi hover giống như một liên kết */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #CFE4FF; /* Màu xanh nhạt xuất hiện khi nhấn vào */\n"
"}")
        self.Autumn.setObjectName("Autumn")
        self.horizontalLayout.addWidget(self.Autumn)
        self.Winter = QtWidgets.QPushButton(parent=self.navBar)
        self.Winter.setStyleSheet("QPushButton {\n"
"    background: transparent; /* Nền trong suốt để lộ màu trắng của NavBar */\n"
"    border: none; /* Không có khung viền */\n"
"    font-size: 14px;\n"
"    font-family: \"Georgia\";\n"
"    color: #4A90E2; /* Chuyển sang màu xanh dương để hợp với tông #CFE4FF */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #0D3B66; /* Màu xanh đậm hơn khi di chuột qua để tạo điểm nhấn */\n"
"    text-decoration: underline; /* Hiện gạch chân khi hover giống như một liên kết */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #CFE4FF; /* Màu xanh nhạt xuất hiện khi nhấn vào */\n"
"}")
        self.Winter.setObjectName("Winter")
        self.horizontalLayout.addWidget(self.Winter)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addWidget(self.navBar)
        self.splitter = QtWidgets.QSplitter(parent=self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(parent=self.splitter)
        self.widget.setMaximumSize(QtCore.QSize(1000, 800))
        self.widget.setStyleSheet("/* Tìm tất cả các widget con có tên bắt đầu bằng \'widget_\' (các Card của bạn) */\n"
"QWidget[objectName^=\"widget_\"] {\n"
"    min-width: 180px;\n"
"    max-width: 180px;\n"
"    min-height: 250px;\n"
"    max-height: 250px;\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);\n"
"\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_37 = QtWidgets.QWidget(parent=self.widget)
        self.widget_37.setStyleSheet("")
        self.widget_37.setObjectName("widget_37")
        self.label_117 = QtWidgets.QLabel(parent=self.widget_37)
        self.label_117.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_117.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_117.setText("")
        self.label_117.setObjectName("label_117")
        self.label_118 = QtWidgets.QLabel(parent=self.widget_37)
        self.label_118.setGeometry(QtCore.QRect(40, 170, 141, 31))
        self.label_118.setStyleSheet(" font-family: \"Georgia\"")
        self.label_118.setObjectName("label_118")
        self.imagecoffee_46 = QtWidgets.QLabel(parent=self.widget_37)
        self.imagecoffee_46.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_46.setText("")
        self.imagecoffee_46.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/yellowsummer.jpg"))
        self.imagecoffee_46.setScaledContents(True)
        self.imagecoffee_46.setObjectName("imagecoffee_46")
        self.buychocolatebalance_93 = QtWidgets.QPushButton(parent=self.widget_37)
        self.buychocolatebalance_93.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_93.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: White; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\images/3507742_cart_ecommerce_grocery_iconoteka_shop_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buychocolatebalance_93.setIcon(icon)
        self.buychocolatebalance_93.setObjectName("buychocolatebalance_93")
        self.gridLayout.addWidget(self.widget_37, 1, 3, 1, 1)
        self.widget_64 = QtWidgets.QWidget(parent=self.widget)
        self.widget_64.setObjectName("widget_64")
        self.label_185 = QtWidgets.QLabel(parent=self.widget_64)
        self.label_185.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_185.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_185.setText("")
        self.label_185.setObjectName("label_185")
        self.label_186 = QtWidgets.QLabel(parent=self.widget_64)
        self.label_186.setGeometry(QtCore.QRect(30, 170, 141, 31))
        self.label_186.setStyleSheet(" font-family: \"Georgia\"")
        self.label_186.setObjectName("label_186")
        self.imagecoffee_80 = QtWidgets.QLabel(parent=self.widget_64)
        self.imagecoffee_80.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_80.setText("")
        self.imagecoffee_80.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/36389bc3ef476ddec430aa38c7c1b41a.jpg"))
        self.imagecoffee_80.setScaledContents(True)
        self.imagecoffee_80.setObjectName("imagecoffee_80")
        self.buychocolatebalance_85 = QtWidgets.QPushButton(parent=self.widget_64)
        self.buychocolatebalance_85.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_85.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: White; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_85.setIcon(icon)
        self.buychocolatebalance_85.setObjectName("buychocolatebalance_85")
        self.gridLayout.addWidget(self.widget_64, 3, 2, 1, 1)
        self.widget_33 = QtWidgets.QWidget(parent=self.widget)
        self.widget_33.setStyleSheet("")
        self.widget_33.setObjectName("widget_33")
        self.label_107 = QtWidgets.QLabel(parent=self.widget_33)
        self.label_107.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_107.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_107.setText("")
        self.label_107.setObjectName("label_107")
        self.label_108 = QtWidgets.QLabel(parent=self.widget_33)
        self.label_108.setGeometry(QtCore.QRect(40, 170, 141, 31))
        self.label_108.setStyleSheet(" font-family: \"Georgia\"")
        self.label_108.setObjectName("label_108")
        self.imagecoffee_41 = QtWidgets.QLabel(parent=self.widget_33)
        self.imagecoffee_41.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_41.setText("")
        self.imagecoffee_41.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/summer.jpg"))
        self.imagecoffee_41.setScaledContents(True)
        self.imagecoffee_41.setObjectName("imagecoffee_41")
        self.buychocolatebalance_97 = QtWidgets.QPushButton(parent=self.widget_33)
        self.buychocolatebalance_97.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_97.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: white; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_97.setIcon(icon)
        self.buychocolatebalance_97.setObjectName("buychocolatebalance_97")
        self.gridLayout.addWidget(self.widget_33, 0, 3, 1, 1)
        self.widget_39 = QtWidgets.QWidget(parent=self.widget)
        self.widget_39.setObjectName("widget_39")
        self.label_121 = QtWidgets.QLabel(parent=self.widget_39)
        self.label_121.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_121.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_121.setText("")
        self.label_121.setObjectName("label_121")
        self.label_122 = QtWidgets.QLabel(parent=self.widget_39)
        self.label_122.setGeometry(QtCore.QRect(30, 170, 141, 31))
        self.label_122.setStyleSheet(" font-family: \"Georgia\"")
        self.label_122.setObjectName("label_122")
        self.imagecoffee_48 = QtWidgets.QLabel(parent=self.widget_39)
        self.imagecoffee_48.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_48.setText("")
        self.imagecoffee_48.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/greenlake.jpg"))
        self.imagecoffee_48.setScaledContents(True)
        self.imagecoffee_48.setObjectName("imagecoffee_48")
        self.buychocolatebalance_92 = QtWidgets.QPushButton(parent=self.widget_39)
        self.buychocolatebalance_92.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_92.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: White; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_92.setIcon(icon)
        self.buychocolatebalance_92.setObjectName("buychocolatebalance_92")
        self.gridLayout.addWidget(self.widget_39, 1, 2, 1, 1)
        self.widget_65 = QtWidgets.QWidget(parent=self.widget)
        self.widget_65.setObjectName("widget_65")
        self.label_187 = QtWidgets.QLabel(parent=self.widget_65)
        self.label_187.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_187.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_187.setText("")
        self.label_187.setObjectName("label_187")
        self.label_188 = QtWidgets.QLabel(parent=self.widget_65)
        self.label_188.setGeometry(QtCore.QRect(30, 170, 141, 31))
        self.label_188.setStyleSheet(" font-family: \"Georgia\"")
        self.label_188.setObjectName("label_188")
        self.imagecoffee_81 = QtWidgets.QLabel(parent=self.widget_65)
        self.imagecoffee_81.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_81.setText("")
        self.imagecoffee_81.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/39ba71c2622a3e6d476b86f6882a987a.jpg"))
        self.imagecoffee_81.setScaledContents(True)
        self.imagecoffee_81.setObjectName("imagecoffee_81")
        self.buychocolatebalance_84 = QtWidgets.QPushButton(parent=self.widget_65)
        self.buychocolatebalance_84.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_84.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: White; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_84.setIcon(icon)
        self.buychocolatebalance_84.setObjectName("buychocolatebalance_84")
        self.gridLayout.addWidget(self.widget_65, 3, 1, 1, 1)
        self.widget_34 = QtWidgets.QWidget(parent=self.widget)
        self.widget_34.setStyleSheet("")
        self.widget_34.setObjectName("widget_34")
        self.label_111 = QtWidgets.QLabel(parent=self.widget_34)
        self.label_111.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_111.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_111.setText("")
        self.label_111.setObjectName("label_111")
        self.label_112 = QtWidgets.QLabel(parent=self.widget_34)
        self.label_112.setGeometry(QtCore.QRect(40, 170, 141, 31))
        self.label_112.setStyleSheet(" font-family: \"Georgia\"")
        self.label_112.setObjectName("label_112")
        self.imagecoffee_43 = QtWidgets.QLabel(parent=self.widget_34)
        self.imagecoffee_43.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_43.setText("")
        self.imagecoffee_43.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/32144f52e3fe45bba60a86e1a5218fb1.jpg"))
        self.imagecoffee_43.setScaledContents(True)
        self.imagecoffee_43.setObjectName("imagecoffee_43")
        self.buychocolatebalance_98 = QtWidgets.QPushButton(parent=self.widget_34)
        self.buychocolatebalance_98.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_98.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: white; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_98.setIcon(icon)
        self.buychocolatebalance_98.setObjectName("buychocolatebalance_98")
        self.gridLayout.addWidget(self.widget_34, 0, 4, 1, 1)
        self.widget_66 = QtWidgets.QWidget(parent=self.widget)
        self.widget_66.setObjectName("widget_66")
        self.label_189 = QtWidgets.QLabel(parent=self.widget_66)
        self.label_189.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_189.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_189.setText("")
        self.label_189.setObjectName("label_189")
        self.label_190 = QtWidgets.QLabel(parent=self.widget_66)
        self.label_190.setGeometry(QtCore.QRect(30, 175, 141, 21))
        self.label_190.setStyleSheet(" font-family: \"Georgia\"")
        self.label_190.setObjectName("label_190")
        self.imagecoffee_82 = QtWidgets.QLabel(parent=self.widget_66)
        self.imagecoffee_82.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_82.setText("")
        self.imagecoffee_82.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/dc6567ac1f25b987742d46805f5e074a.jpg"))
        self.imagecoffee_82.setScaledContents(True)
        self.imagecoffee_82.setObjectName("imagecoffee_82")
        self.buychocolatebalance_83 = QtWidgets.QPushButton(parent=self.widget_66)
        self.buychocolatebalance_83.setGeometry(QtCore.QRect(30, 200, 121, 41))
        self.buychocolatebalance_83.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: White; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_83.setIcon(icon)
        self.buychocolatebalance_83.setObjectName("buychocolatebalance_83")
        self.gridLayout.addWidget(self.widget_66, 3, 3, 1, 1)
        self.widget_31 = QtWidgets.QWidget(parent=self.widget)
        self.widget_31.setObjectName("widget_31")
        self.label_103 = QtWidgets.QLabel(parent=self.widget_31)
        self.label_103.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_103.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_103.setText("")
        self.label_103.setObjectName("label_103")
        self.label_104 = QtWidgets.QLabel(parent=self.widget_31)
        self.label_104.setGeometry(QtCore.QRect(40, 170, 141, 31))
        self.label_104.setStyleSheet(" font-family: \"Georgia\"")
        self.label_104.setObjectName("label_104")
        self.imagecoffee_39 = QtWidgets.QLabel(parent=self.widget_31)
        self.imagecoffee_39.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_39.setStyleSheet("border-radius: 20px;")
        self.imagecoffee_39.setText("")
        self.imagecoffee_39.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/74bc4908e5697cb42af594c4713df14c.jpg"))
        self.imagecoffee_39.setScaledContents(True)
        self.imagecoffee_39.setObjectName("imagecoffee_39")
        self.buychocolatebalance_95 = QtWidgets.QPushButton(parent=self.widget_31)
        self.buychocolatebalance_95.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_95.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: white; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_95.setIcon(icon)
        self.buychocolatebalance_95.setObjectName("buychocolatebalance_95")
        self.gridLayout.addWidget(self.widget_31, 0, 1, 1, 1)
        self.widget_32 = QtWidgets.QWidget(parent=self.widget)
        self.widget_32.setObjectName("widget_32")
        self.label_105 = QtWidgets.QLabel(parent=self.widget_32)
        self.label_105.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_105.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_105.setText("")
        self.label_105.setObjectName("label_105")
        self.label_106 = QtWidgets.QLabel(parent=self.widget_32)
        self.label_106.setGeometry(QtCore.QRect(40, 170, 141, 31))
        self.label_106.setStyleSheet(" font-family: \"Georgia\"")
        self.label_106.setObjectName("label_106")
        self.imagecoffee_40 = QtWidgets.QLabel(parent=self.widget_32)
        self.imagecoffee_40.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_40.setStyleSheet("border-radius: 20px;")
        self.imagecoffee_40.setText("")
        self.imagecoffee_40.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/76ff2c0e2bda87e3a7efbf02d3128c3d.jpg"))
        self.imagecoffee_40.setScaledContents(True)
        self.imagecoffee_40.setObjectName("imagecoffee_40")
        self.buychocolatebalance_96 = QtWidgets.QPushButton(parent=self.widget_32)
        self.buychocolatebalance_96.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_96.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: white; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_96.setIcon(icon)
        self.buychocolatebalance_96.setObjectName("buychocolatebalance_96")
        self.gridLayout.addWidget(self.widget_32, 0, 2, 1, 1)
        self.widget_30 = QtWidgets.QWidget(parent=self.widget)
        self.widget_30.setMaximumSize(QtCore.QSize(200, 258))
        self.widget_30.setObjectName("widget_30")
        self.label_101 = QtWidgets.QLabel(parent=self.widget_30)
        self.label_101.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_101.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_101.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_101.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_101.setText("")
        self.label_101.setScaledContents(True)
        self.label_101.setObjectName("label_101")
        self.label_102 = QtWidgets.QLabel(parent=self.widget_30)
        self.label_102.setGeometry(QtCore.QRect(30, 170, 141, 31))
        self.label_102.setStyleSheet(" font-family: \"Georgia\"")
        self.label_102.setObjectName("label_102")
        self.imagecoffee_38 = QtWidgets.QLabel(parent=self.widget_30)
        self.imagecoffee_38.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_38.setText("")
        self.imagecoffee_38.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/white.jpg"))
        self.imagecoffee_38.setScaledContents(True)
        self.imagecoffee_38.setObjectName("imagecoffee_38")
        self.buychocolatebalance_94 = QtWidgets.QPushButton(parent=self.widget_30)
        self.buychocolatebalance_94.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_94.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: white;\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_94.setIcon(icon)
        self.buychocolatebalance_94.setObjectName("buychocolatebalance_94")
        self.gridLayout.addWidget(self.widget_30, 0, 0, 1, 1)
        self.widget_62 = QtWidgets.QWidget(parent=self.widget)
        self.widget_62.setObjectName("widget_62")
        self.label_181 = QtWidgets.QLabel(parent=self.widget_62)
        self.label_181.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_181.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_181.setText("")
        self.label_181.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/plus.png"))
        self.label_181.setObjectName("label_181")
        self.buychocolatebalance_79 = QtWidgets.QPushButton(parent=self.widget_62)
        self.buychocolatebalance_79.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_79.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: White; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_79.setIcon(icon)
        self.buychocolatebalance_79.setObjectName("buychocolatebalance_79")
        self.imagecoffee_78 = QtWidgets.QLabel(parent=self.widget_62)
        self.imagecoffee_78.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_78.setText("")
        self.imagecoffee_78.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/plus.png"))
        self.imagecoffee_78.setScaledContents(True)
        self.imagecoffee_78.setObjectName("imagecoffee_78")
        self.gridLayout.addWidget(self.widget_62, 3, 4, 1, 1)
        self.widget_63 = QtWidgets.QWidget(parent=self.widget)
        self.widget_63.setMaximumSize(QtCore.QSize(200, 258))
        self.widget_63.setObjectName("widget_63")
        self.label_183 = QtWidgets.QLabel(parent=self.widget_63)
        self.label_183.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_183.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_183.setText("")
        self.label_183.setObjectName("label_183")
        self.label_184 = QtWidgets.QLabel(parent=self.widget_63)
        self.label_184.setGeometry(QtCore.QRect(30, 170, 141, 31))
        self.label_184.setStyleSheet(" font-family: \"Georgia\"")
        self.label_184.setObjectName("label_184")
        self.imagecoffee_79 = QtWidgets.QLabel(parent=self.widget_63)
        self.imagecoffee_79.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_79.setText("")
        self.imagecoffee_79.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/a13d710c6e412c6e53965f8b65aeac70.jpg"))
        self.imagecoffee_79.setScaledContents(True)
        self.imagecoffee_79.setObjectName("imagecoffee_79")
        self.buychocolatebalance_89 = QtWidgets.QPushButton(parent=self.widget_63)
        self.buychocolatebalance_89.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_89.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"        color: White;/* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_89.setIcon(icon)
        self.buychocolatebalance_89.setObjectName("buychocolatebalance_89")
        self.gridLayout.addWidget(self.widget_63, 3, 0, 1, 1)
        self.widget_35 = QtWidgets.QWidget(parent=self.widget)
        self.widget_35.setStyleSheet("")
        self.widget_35.setObjectName("widget_35")
        self.label_113 = QtWidgets.QLabel(parent=self.widget_35)
        self.label_113.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_113.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_113.setText("")
        self.label_113.setObjectName("label_113")
        self.label_114 = QtWidgets.QLabel(parent=self.widget_35)
        self.label_114.setGeometry(QtCore.QRect(40, 170, 141, 31))
        self.label_114.setStyleSheet(" font-family: \"Georgia\"")
        self.label_114.setObjectName("label_114")
        self.imagecoffee_44 = QtWidgets.QLabel(parent=self.widget_35)
        self.imagecoffee_44.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_44.setText("")
        self.imagecoffee_44.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/snowman.jpg"))
        self.imagecoffee_44.setScaledContents(True)
        self.imagecoffee_44.setObjectName("imagecoffee_44")
        self.buychocolatebalance_99 = QtWidgets.QPushButton(parent=self.widget_35)
        self.buychocolatebalance_99.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_99.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: White; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_99.setIcon(icon)
        self.buychocolatebalance_99.setObjectName("buychocolatebalance_99")
        self.gridLayout.addWidget(self.widget_35, 1, 4, 1, 1)
        self.widget_38 = QtWidgets.QWidget(parent=self.widget)
        self.widget_38.setMaximumSize(QtCore.QSize(200, 258))
        self.widget_38.setObjectName("widget_38")
        self.label_119 = QtWidgets.QLabel(parent=self.widget_38)
        self.label_119.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_119.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_119.setText("")
        self.label_119.setObjectName("label_119")
        self.label_120 = QtWidgets.QLabel(parent=self.widget_38)
        self.label_120.setGeometry(QtCore.QRect(40, 170, 121, 31))
        self.label_120.setStyleSheet(" font-family: \"Georgia\"")
        self.label_120.setObjectName("label_120")
        self.imagecoffee_47 = QtWidgets.QLabel(parent=self.widget_38)
        self.imagecoffee_47.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_47.setText("")
        self.imagecoffee_47.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/d60f12a16546fd232f3419e0b35493ae.jpg"))
        self.imagecoffee_47.setScaledContents(True)
        self.imagecoffee_47.setObjectName("imagecoffee_47")
        self.buychocolatebalance_90 = QtWidgets.QPushButton(parent=self.widget_38)
        self.buychocolatebalance_90.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_90.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: White; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_90.setIcon(icon)
        self.buychocolatebalance_90.setObjectName("buychocolatebalance_90")
        self.gridLayout.addWidget(self.widget_38, 1, 0, 1, 1)
        self.widget_36 = QtWidgets.QWidget(parent=self.widget)
        self.widget_36.setObjectName("widget_36")
        self.label_115 = QtWidgets.QLabel(parent=self.widget_36)
        self.label_115.setGeometry(QtCore.QRect(30, 10, 141, 161))
        self.label_115.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_115.setText("")
        self.label_115.setObjectName("label_115")
        self.label_116 = QtWidgets.QLabel(parent=self.widget_36)
        self.label_116.setGeometry(QtCore.QRect(40, 170, 141, 31))
        self.label_116.setStyleSheet(" font-family: \"Georgia\"")
        self.label_116.setObjectName("label_116")
        self.imagecoffee_45 = QtWidgets.QLabel(parent=self.widget_36)
        self.imagecoffee_45.setGeometry(QtCore.QRect(40, 20, 121, 141))
        self.imagecoffee_45.setText("")
        self.imagecoffee_45.setPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/Fleur.jpg"))
        self.imagecoffee_45.setScaledContents(True)
        self.imagecoffee_45.setObjectName("imagecoffee_45")
        self.buychocolatebalance_91 = QtWidgets.QPushButton(parent=self.widget_36)
        self.buychocolatebalance_91.setGeometry(QtCore.QRect(40, 200, 121, 41))
        self.buychocolatebalance_91.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: White; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_91.setIcon(icon)
        self.buychocolatebalance_91.setObjectName("buychocolatebalance_91")
        self.gridLayout.addWidget(self.widget_36, 1, 1, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.splitter)
        self.frame.setMaximumSize(QtCore.QSize(410, 800))
        self.frame.setStyleSheet("border: 1px solid rgb(67, 139, 196);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.tableWidget.setMaximumSize(QtCore.QSize(16777215, 600))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(-1)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    background-color: #e6f4fa;\n"
"    alternate-background-color: #E1EFFF;\n"
"    font-family: \"Georgia\";\n"
"    font-size: 14px;\n"
"    gridline-color: #CFE4FF;\n"
"\n"
"    border: 2px solid #A6C8FF;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"/* Header container */\n"
"QHeaderView {\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* Header cells */\n"
"QHeaderView::section {\n"
"    background-color: #e6f4fa;\n"
"    color: #0D3B66;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    height: 32px;\n"
"\n"
"    border: none;              /* bỏ border để không lệch */\n"
"    border-bottom: 1px solid #A6C8FF;\n"
"}\n"
"\n"
"/* bo góc trái */\n"
"QHeaderView::section:first {\n"
"    border-top-left-radius: 20px;\n"
"}\n"
"\n"
"/* bo góc phải */\n"
"QHeaderView::section:last {\n"
"    border-top-right-radius: 20px;\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Georgia")
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.widget_2 = QtWidgets.QWidget(parent=self.frame)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 85))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 85))
        self.widget_2.setStyleSheet("\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.lineEdit_PhoneNum_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit_PhoneNum_2.setGeometry(QtCore.QRect(180, 10, 121, 31))
        self.lineEdit_PhoneNum_2.setStyleSheet("color: rgb(11, 11, 11);\n"
"border: 1px solid rgb(67, 139, 196);")
        self.lineEdit_PhoneNum_2.setText("")
        self.lineEdit_PhoneNum_2.setObjectName("lineEdit_PhoneNum_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.label_3.setStyleSheet(" font-family: \"Georgia\";\n"
"color: rgb(67, 139, 196);\n"
"border: 1px solid rgb(67, 139, 196);\n"
"")
        self.label_3.setObjectName("label_3")
        self.pushButton_loadCusType_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_loadCusType_2.setGeometry(QtCore.QRect(310, 10, 31, 31))
        self.pushButton_loadCusType_2.setStyleSheet("color: rgb(18, 18, 18);\n"
"border: 1px solid rgb(67, 139, 196);")
        self.pushButton_loadCusType_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/ic_search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_loadCusType_2.setIcon(icon1)
        self.pushButton_loadCusType_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_loadCusType_2.setObjectName("pushButton_loadCusType_2")
        self.label_14 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 161, 31))
        self.label_14.setStyleSheet(" font-family: \"Georgia\";\n"
"color: rgb(67, 139, 196);\n"
"border: 1px solid rgb(67, 139, 196);")
        self.label_14.setObjectName("label_14")
        self.lineEdit_CustomerType_3 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.lineEdit_CustomerType_3.setGeometry(QtCore.QRect(180, 50, 121, 31))
        self.lineEdit_CustomerType_3.setStyleSheet("color: rgb(11, 11, 11);\n"
"border: 1px solid rgb(67, 139, 196);")
        self.lineEdit_CustomerType_3.setObjectName("lineEdit_CustomerType_3")
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(parent=self.frame)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 54))
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_3.setStyleSheet("\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.label_11 = QtWidgets.QLabel(parent=self.widget_3)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.label_11.setStyleSheet(" font-family: \"Georgia\";\n"
"color: rgb(67, 139, 196);\n"
"border: 1px solid rgb(67, 139, 196);")
        self.label_11.setObjectName("label_11")
        self.lineEdit_TotalBill = QtWidgets.QLineEdit(parent=self.widget_3)
        self.lineEdit_TotalBill.setGeometry(QtCore.QRect(180, 10, 151, 31))
        self.lineEdit_TotalBill.setStyleSheet("color: rgb(11, 11, 11);\n"
"border: 1px solid rgb(67, 139, 196);")
        self.lineEdit_TotalBill.setObjectName("lineEdit_TotalBill")
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(parent=self.frame)
        self.widget_5.setStyleSheet("\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_TB_9 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_TB_9.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_TB_9.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: #4A90E2; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/ic_check.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_TB_9.setIcon(icon2)
        self.pushButton_TB_9.setIconSize(QtCore.QSize(30, 20))
        self.pushButton_TB_9.setObjectName("pushButton_TB_9")
        self.gridLayout_3.addWidget(self.pushButton_TB_9, 1, 1, 1, 1)
        self.pushButton_TB_10 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_TB_10.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_TB_10.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: #4A90E2; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/ic_removenail.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_TB_10.setIcon(icon3)
        self.pushButton_TB_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_TB_10.setObjectName("pushButton_TB_10")
        self.gridLayout_3.addWidget(self.pushButton_TB_10, 1, 0, 1, 1)
        self.pushButton_TB_16 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_TB_16.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_TB_16.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: #4A90E2; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/ic_exit.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_TB_16.setIcon(icon4)
        self.pushButton_TB_16.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_TB_16.setObjectName("pushButton_TB_16")
        self.gridLayout_3.addWidget(self.pushButton_TB_16, 2, 1, 1, 1)
        self.pushButton_TB_11 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_TB_11.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.OpenHandCursor))
        self.pushButton_TB_11.setStyleSheet("QPushButton {\n"
"    background-color:rgb(167, 212, 238); /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: #4A90E2; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid rgb(67, 139, 196); /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("D:\\UEL\\PythonProject\\CustomerManagement\\ui\\../images/ic_selecttech.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_TB_11.setIcon(icon5)
        self.pushButton_TB_11.setIconSize(QtCore.QSize(40, 20))
        self.pushButton_TB_11.setObjectName("pushButton_TB_11")
        self.gridLayout_3.addWidget(self.pushButton_TB_11, 2, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.verticalLayout_4.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1407, 22))
        self.menubar.setObjectName("menubar")
        self.menuMENU = QtWidgets.QMenu(parent=self.menubar)
        self.menuMENU.setObjectName("menuMENU")
        self.menuMore_about_us = QtWidgets.QMenu(parent=self.menubar)
        self.menuMore_about_us.setObjectName("menuMore_about_us")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSpring = QtGui.QAction(parent=MainWindow)
        self.actionSpring.setObjectName("actionSpring")
        self.actionSummer = QtGui.QAction(parent=MainWindow)
        self.actionSummer.setObjectName("actionSummer")
        self.actionAutumn = QtGui.QAction(parent=MainWindow)
        self.actionAutumn.setObjectName("actionAutumn")
        self.actionWinter = QtGui.QAction(parent=MainWindow)
        self.actionWinter.setObjectName("actionWinter")
        self.menuMENU.addAction(self.actionSpring)
        self.menuMENU.addAction(self.actionSummer)
        self.menuMENU.addAction(self.actionAutumn)
        self.menuMENU.addAction(self.actionWinter)
        self.menubar.addAction(self.menuMENU.menuAction())
        self.menubar.addAction(self.menuMore_about_us.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MY NAIL SHOP"))
        self.label_10.setText(_translate("MainWindow", "Where Your Beauty and Satisfaction Come First"))
        self.Spring.setText(_translate("MainWindow", "Spring"))
        self.Summer.setText(_translate("MainWindow", "Summer"))
        self.Autumn.setText(_translate("MainWindow", "Autumn"))
        self.Winter.setText(_translate("MainWindow", "Winter"))
        self.label_118.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#438bc4;\">Sunny Side Up</span><span style=\" color:#438bc4;\"> - 26$</span></p></body></html>"))
        self.buychocolatebalance_93.setText(_translate("MainWindow", "Select Design"))
        self.label_186.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438bc4;\">Inimalist Red Ribbon - 30$</span></p></body></html>"))
        self.buychocolatebalance_85.setText(_translate("MainWindow", "Select Design"))
        self.label_108.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438bc4;\">Ocean Pearl Dream- 40$</span></p></body></html>"))
        self.buychocolatebalance_97.setText(_translate("MainWindow", "Select Design"))
        self.label_122.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438bc4;\">Green Matcha Muse- 36$</span></p></body></html>"))
        self.buychocolatebalance_92.setText(_translate("MainWindow", "Select Design"))
        self.label_188.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438bc4;\">Butterfly Garden Glow - 36$</span></p></body></html>"))
        self.buychocolatebalance_84.setText(_translate("MainWindow", "Select Design"))
        self.label_112.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438bc4;\">Purple Amethyst Glaze - 36$</span></p></body></html>"))
        self.buychocolatebalance_98.setText(_translate("MainWindow", "Select Design"))
        self.label_190.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-style:italic; color:#438bc4;\">Creamy Heart Pearl</span><span style=\" color:#438bc4;\">- 32$</span></p></body></html>"))
        self.buychocolatebalance_83.setText(_translate("MainWindow", "Select Design"))
        self.label_104.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438bc4;\">Yellow Daisy Garden - 30$</span></p></body></html>"))
        self.buychocolatebalance_95.setText(_translate("MainWindow", "Select Design"))
        self.label_106.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438bc4;\">Silver Ribbon Dew - 25$</span></p></body></html>"))
        self.buychocolatebalance_96.setText(_translate("MainWindow", "Select Design"))
        self.label_102.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438ac3;\">White Flora Charm - 36$</span></p></body></html>"))
        self.buychocolatebalance_94.setText(_translate("MainWindow", "Select Design"))
        self.buychocolatebalance_79.setText(_translate("MainWindow", "Self-custom"))
        self.label_184.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438bc4;\">Cosmic Marble Pink - 36$</span></p></body></html>"))
        self.buychocolatebalance_89.setText(_translate("MainWindow", "Select Design"))
        self.label_114.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438bc4;\">Winter Snowman - 30$</span></p></body></html>"))
        self.buychocolatebalance_99.setText(_translate("MainWindow", "Select Design"))
        self.label_120.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438bc4;\">Pink Crystal Fairy - 36$</span></p></body></html>"))
        self.buychocolatebalance_90.setText(_translate("MainWindow", "Select Design"))
        self.label_116.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#438bc4;\">Sparkling Starlight - 37$</span></p></body></html>"))
        self.buychocolatebalance_91.setText(_translate("MainWindow", "Select Design"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Items"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Quantity"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Price"))
        self.label_3.setText(_translate("MainWindow", "Customer\'s Phone Number:"))
        self.label_14.setText(_translate("MainWindow", "Customer\'s Type:"))
        self.label_11.setText(_translate("MainWindow", "Total Bill: "))
        self.pushButton_TB_9.setText(_translate("MainWindow", "Check out"))
        self.pushButton_TB_10.setText(_translate("MainWindow", "Remove"))
        self.pushButton_TB_16.setText(_translate("MainWindow", "Log out"))
        self.pushButton_TB_11.setText(_translate("MainWindow", "Select Technician"))
        self.menuMENU.setTitle(_translate("MainWindow", "MENU"))
        self.menuMore_about_us.setTitle(_translate("MainWindow", "More about us"))
        self.actionSpring.setText(_translate("MainWindow", "Spring"))
        self.actionSummer.setText(_translate("MainWindow", "Summer"))
        self.actionAutumn.setText(_translate("MainWindow", "Autumn"))
        self.actionWinter.setText(_translate("MainWindow", "Winter"))
