# Form implementation generated from reading ui file 'C:\Users\Windows\PycharmProjects\ktlt-uel\k25411\ui\ProductMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1195, 723)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(234, 242, 251);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-2, 0, 1151, 41))
        self.label.setStyleSheet("background-color: rgb(167, 212, 238);\n"
"color: rgb(15,40,80);\n"
"font: 50 20pt \"Alex Brush\";\n"
"border-radius: 20px;\n"
"border: 2px solid rgb(67, 139, 196);\n"
"    border-radius: 12px;\n"
"")
        self.label.setObjectName("label")
        self.tableWidgetSample = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetSample.setGeometry(QtCore.QRect(10, 50, 381, 381))
        self.tableWidgetSample.setStyleSheet("border: 2px solid rgb(170,210,250);\n"
"font: 9pt \"Rockwell\";\n"
"background-color: rgb(234, 242, 251);\n"
"color: rgb(0, 0, 127);\n"
"")
        self.tableWidgetSample.setObjectName("tableWidgetSample")
        self.tableWidgetSample.setColumnCount(4)
        self.tableWidgetSample.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetSample.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSample.setItem(0, 1, item)
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 440, 381, 191))
        self.groupBox.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("QWidget {\n"
"    font: 75 16pt \"Rockwell\";\n"
"    color: rgb(45, 5, 127);\n"
"     background-color: rgb(167, 212, 238);\n"
"    border-radius: 20px;\n"
"border: 2px solid rgb(67, 139, 196);\n"
"}")
        self.groupBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 151, 21))
        self.label_2.setStyleSheet("font: italic 12pt \"Rockwell\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 151, 21))
        self.label_3.setStyleSheet("font: italic 12pt \"Rockwell\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 151, 21))
        self.label_4.setStyleSheet("font: italic 12pt \"Rockwell\";")
        self.label_4.setObjectName("label_4")
        self.pushButtonSampleSave = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSampleSave.setGeometry(QtCore.QRect(10, 150, 81, 31))
        self.pushButtonSampleSave.setStyleSheet("background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);\n"
"QPushButton{\n"
"    background-color:#4E86B5;\n"
"    border:none;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Windows\\PycharmProjects\\ktlt-uel\\k25411\\ui\\../../../../.designer/images/ic_save(2).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSampleSave.setIcon(icon)
        self.pushButtonSampleSave.setIconSize(QtCore.QSize(40, 25))
        self.pushButtonSampleSave.setAutoRepeatInterval(99)
        self.pushButtonSampleSave.setObjectName("pushButtonSampleSave")
        self.pushButtonSampleClear = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSampleClear.setGeometry(QtCore.QRect(90, 150, 91, 31))
        self.pushButtonSampleClear.setStyleSheet("background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\Windows\\PycharmProjects\\ktlt-uel\\k25411\\ui\\../../../../.designer/images/ic_clear (2).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSampleClear.setIcon(icon1)
        self.pushButtonSampleClear.setIconSize(QtCore.QSize(40, 25))
        self.pushButtonSampleClear.setObjectName("pushButtonSampleClear")
        self.pushButtonSampleSearch = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSampleSearch.setGeometry(QtCore.QRect(180, 150, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonSampleSearch.setFont(font)
        self.pushButtonSampleSearch.setStyleSheet("background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\Windows\\PycharmProjects\\ktlt-uel\\k25411\\ui\\../../../../.designer/images/ic_search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSampleSearch.setIcon(icon2)
        self.pushButtonSampleSearch.setIconSize(QtCore.QSize(40, 25))
        self.pushButtonSampleSearch.setObjectName("pushButtonSampleSearch")
        self.pushButtonSampleRemove = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSampleRemove.setGeometry(QtCore.QRect(271, 150, 101, 31))
        self.pushButtonSampleRemove.setStyleSheet("background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\Windows\\PycharmProjects\\ktlt-uel\\k25411\\ui\\../../../../.designer/images/ic_remove.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSampleRemove.setIcon(icon3)
        self.pushButtonSampleRemove.setIconSize(QtCore.QSize(40, 25))
        self.pushButtonSampleRemove.setObjectName("pushButtonSampleRemove")
        self.lineEditSampleID = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditSampleID.setGeometry(QtCore.QRect(180, 30, 191, 20))
        self.lineEditSampleID.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.lineEditSampleID.setObjectName("lineEditSampleID")
        self.lineEditSampleName = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditSampleName.setGeometry(QtCore.QRect(180, 60, 191, 20))
        self.lineEditSampleName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditSampleName.setObjectName("lineEditSampleName")
        self.lineEditPrice = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPrice.setGeometry(QtCore.QRect(180, 90, 191, 20))
        self.lineEditPrice.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditPrice.setObjectName("lineEditPrice")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 120, 151, 21))
        self.label_12.setStyleSheet("font: italic 12pt \"Rockwell\";")
        self.label_12.setObjectName("label_12")
        self.lineEditSampleQuantity = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditSampleQuantity.setGeometry(QtCore.QRect(180, 120, 191, 20))
        self.lineEditSampleQuantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditSampleQuantity.setObjectName("lineEditSampleQuantity")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 440, 361, 191))
        self.groupBox_2.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet("QWidget {\n"
"    font: 75 16pt \"Rockwell\";\n"
"    color: rgb(45, 5, 127);\n"
"     background-color: rgb(167, 212, 238);\n"
"    border-radius: 20px;\n"
"border: 2px solid rgb(67, 139, 196);\n"
"}")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 171, 21))
        self.label_5.setStyleSheet("font: italic 12pt \"Rockwell\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 171, 21))
        self.label_6.setStyleSheet("font: italic 12pt \"Rockwell\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 171, 21))
        self.label_7.setStyleSheet("font: italic 12pt \"Rockwell\";\n"
"")
        self.label_7.setObjectName("label_7")
        self.lineEditCustomerUserName = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditCustomerUserName.setGeometry(QtCore.QRect(190, 30, 161, 20))
        self.lineEditCustomerUserName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditCustomerUserName.setObjectName("lineEditCustomerUserName")
        self.lineEditPhoneNumber = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditPhoneNumber.setGeometry(QtCore.QRect(190, 60, 161, 20))
        self.lineEditPhoneNumber.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditPhoneNumber.setObjectName("lineEditPhoneNumber")
        self.lineEditType = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditType.setGeometry(QtCore.QRect(190, 90, 161, 20))
        self.lineEditType.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditType.setObjectName("lineEditType")
        self.pushButtonCustomerSave = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonCustomerSave.setGeometry(QtCore.QRect(10, 150, 81, 31))
        self.pushButtonCustomerSave.setStyleSheet("background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);")
        self.pushButtonCustomerSave.setIcon(icon)
        self.pushButtonCustomerSave.setIconSize(QtCore.QSize(40, 23))
        self.pushButtonCustomerSave.setObjectName("pushButtonCustomerSave")
        self.pushButtonCustomerClear = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonCustomerClear.setGeometry(QtCore.QRect(90, 150, 81, 31))
        self.pushButtonCustomerClear.setStyleSheet("background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);")
        self.pushButtonCustomerClear.setIcon(icon1)
        self.pushButtonCustomerClear.setIconSize(QtCore.QSize(40, 23))
        self.pushButtonCustomerClear.setObjectName("pushButtonCustomerClear")
        self.pushButtonCustomerSearch = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonCustomerSearch.setGeometry(QtCore.QRect(170, 150, 91, 31))
        self.pushButtonCustomerSearch.setStyleSheet("\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);\n"
"background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);")
        self.pushButtonCustomerSearch.setIcon(icon2)
        self.pushButtonCustomerSearch.setIconSize(QtCore.QSize(40, 23))
        self.pushButtonCustomerSearch.setObjectName("pushButtonCustomerSearch")
        self.pushButtonCustomerRemove = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButtonCustomerRemove.setGeometry(QtCore.QRect(260, 150, 91, 31))
        self.pushButtonCustomerRemove.setStyleSheet("background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);")
        self.pushButtonCustomerRemove.setIcon(icon3)
        self.pushButtonCustomerRemove.setIconSize(QtCore.QSize(40, 22))
        self.pushButtonCustomerRemove.setObjectName("pushButtonCustomerRemove")
        self.pushButtonCustomerSearch.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.lineEditCustomerUserName.raise_()
        self.lineEditPhoneNumber.raise_()
        self.lineEditType.raise_()
        self.pushButtonCustomerSave.raise_()
        self.pushButtonCustomerClear.raise_()
        self.pushButtonCustomerRemove.raise_()
        self.dateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(1000, 50, 151, 51))
        self.dateEdit.setMaximumSize(QtCore.QSize(321, 16777215))
        self.dateEdit.setStyleSheet("font: 14pt \"Rockwell Condensed\";\n"
"background-color: rgb(207, 228, 255);\n"
"border-radius: 20px;\n"
"border: 2px solid rgb(170,210,250);")
        self.dateEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.dateEdit.setObjectName("dateEdit")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(400, 50, 191, 121))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.groupBox_5.setAutoFillBackground(False)
        self.groupBox_5.setStyleSheet("font: 75 14pt \"Rockwell\";\n"
"border: 2px solid rgb(170,210,250);\n"
"background-color: rgb(207, 228, 255);\n"
"color: rgb(45, 5, 127);\n"
"border-radius: 20px;")
        self.groupBox_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setCheckable(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButtonOpenChartFeedback = QtWidgets.QPushButton(parent=self.groupBox_5)
        self.pushButtonOpenChartFeedback.setGeometry(QtCore.QRect(30, 80, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonOpenChartFeedback.setFont(font)
        self.pushButtonOpenChartFeedback.setStyleSheet("background-color: rgb(67, 139, 196);\n"
"color: rgb(224, 253, 255);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\Windows\\PycharmProjects\\ktlt-uel\\k25411\\ui\\../../../../.designer/images/ic_feedback.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOpenChartFeedback.setIcon(icon4)
        self.pushButtonOpenChartFeedback.setIconSize(QtCore.QSize(40, 20))
        self.pushButtonOpenChartFeedback.setObjectName("pushButtonOpenChartFeedback")
        self.tableWidgetCustomer = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetCustomer.setGeometry(QtCore.QRect(400, 180, 361, 251))
        self.tableWidgetCustomer.setStyleSheet("font: 9pt \"Rockwell\";\n"
"color: rgb(0, 0, 127);\n"
"background-color: rgb(234, 242, 251);\n"
"border: 2px solid rgb(170,210,250);")
        self.tableWidgetCustomer.setObjectName("tableWidgetCustomer")
        self.tableWidgetCustomer.setColumnCount(3)
        self.tableWidgetCustomer.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetCustomer.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetCustomer.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetCustomer.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetCustomer.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetCustomer.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetCustomer.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetCustomer.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetCustomer.setHorizontalHeaderItem(2, item)
        self.tableWidgetEmployee = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetEmployee.setGeometry(QtCore.QRect(770, 180, 381, 251))
        self.tableWidgetEmployee.setStyleSheet("font: 9pt \"Rockwell\";\n"
"color: rgb(0, 0, 127);\n"
"background-color: rgb(234, 242, 251);\n"
"border: 2px solid rgb(170,210,250);\n"
"")
        self.tableWidgetEmployee.setObjectName("tableWidgetEmployee")
        self.tableWidgetEmployee.setColumnCount(4)
        self.tableWidgetEmployee.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetEmployee.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetEmployee.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetEmployee.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetEmployee.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetEmployee.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetEmployee.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetEmployee.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(175, 203, 243))
        self.tableWidgetEmployee.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetEmployee.setHorizontalHeaderItem(3, item)
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(770, 440, 381, 191))
        self.groupBox_6.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.groupBox_6.setAutoFillBackground(False)
        self.groupBox_6.setStyleSheet("QWidget {\n"
"    font: 75 16pt \"Rockwell\";\n"
"    color: rgb(45, 5, 127);\n"
"     background-color: rgb(167, 212, 238);\n"
"    border-radius: 20px;\n"
"border: 2px solid rgb(67, 139, 196);\n"
"}")
        self.groupBox_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 161, 21))
        self.label_8.setStyleSheet("font: italic 12pt \"Rockwell\";\n"
"")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_9.setGeometry(QtCore.QRect(10, 60, 161, 21))
        self.label_9.setStyleSheet("font: italic 12pt \"Rockwell\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(10, 90, 161, 21))
        self.label_10.setStyleSheet("font: italic 12pt \"Rockwell\";")
        self.label_10.setObjectName("label_10")
        self.lineEditEmployeeID = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEditEmployeeID.setGeometry(QtCore.QRect(190, 30, 171, 20))
        self.lineEditEmployeeID.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditEmployeeID.setObjectName("lineEditEmployeeID")
        self.lineEditEmployeeName = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEditEmployeeName.setGeometry(QtCore.QRect(190, 60, 171, 20))
        self.lineEditEmployeeName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditEmployeeName.setObjectName("lineEditEmployeeName")
        self.lineEditExperience = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEditExperience.setGeometry(QtCore.QRect(190, 90, 171, 20))
        self.lineEditExperience.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditExperience.setObjectName("lineEditExperience")
        self.pushButtonEmployeeSave = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.pushButtonEmployeeSave.setGeometry(QtCore.QRect(10, 150, 81, 31))
        self.pushButtonEmployeeSave.setStyleSheet("\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);")
        self.pushButtonEmployeeSave.setIcon(icon)
        self.pushButtonEmployeeSave.setIconSize(QtCore.QSize(40, 25))
        self.pushButtonEmployeeSave.setObjectName("pushButtonEmployeeSave")
        self.pushButtonEmployeeClear = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.pushButtonEmployeeClear.setGeometry(QtCore.QRect(90, 150, 81, 31))
        self.pushButtonEmployeeClear.setStyleSheet("\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);")
        self.pushButtonEmployeeClear.setIcon(icon1)
        self.pushButtonEmployeeClear.setIconSize(QtCore.QSize(40, 25))
        self.pushButtonEmployeeClear.setObjectName("pushButtonEmployeeClear")
        self.pushButtonEmployeeSearch = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.pushButtonEmployeeSearch.setGeometry(QtCore.QRect(170, 150, 91, 31))
        self.pushButtonEmployeeSearch.setStyleSheet("\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);")
        self.pushButtonEmployeeSearch.setIcon(icon2)
        self.pushButtonEmployeeSearch.setIconSize(QtCore.QSize(40, 25))
        self.pushButtonEmployeeSearch.setObjectName("pushButtonEmployeeSearch")
        self.pushButtonEmployeeRemove = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.pushButtonEmployeeRemove.setGeometry(QtCore.QRect(260, 150, 101, 31))
        self.pushButtonEmployeeRemove.setStyleSheet("\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);background-color: rgb(67, 139, 196);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"color: rgb(224, 253, 255);")
        self.pushButtonEmployeeRemove.setIcon(icon3)
        self.pushButtonEmployeeRemove.setIconSize(QtCore.QSize(40, 25))
        self.pushButtonEmployeeRemove.setObjectName("pushButtonEmployeeRemove")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(10, 120, 161, 21))
        self.label_11.setStyleSheet("font: italic 12pt \"Rockwell\";")
        self.label_11.setObjectName("label_11")
        self.lineEditCustomerBooked = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.lineEditCustomerBooked.setGeometry(QtCore.QRect(190, 120, 171, 20))
        self.lineEditCustomerBooked.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditCustomerBooked.setObjectName("lineEditCustomerBooked")
        self.groupBox_7 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(600, 50, 191, 121))
        self.groupBox_7.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.groupBox_7.setAutoFillBackground(False)
        self.groupBox_7.setStyleSheet("font: 75 14pt \"Rockwell\";\n"
"background-color: rgb(207, 228, 255);\n"
"color: rgb(45, 5, 127);\n"
"border-radius: 20px;\n"
"border: 2px solid rgb(170,210,250);")
        self.groupBox_7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setCheckable(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButtonSampleQuantity = QtWidgets.QPushButton(parent=self.groupBox_7)
        self.pushButtonSampleQuantity.setGeometry(QtCore.QRect(30, 80, 121, 31))
        self.pushButtonSampleQuantity.setStyleSheet("background-color: rgb(67, 139, 196);\n"
"color: rgb(224, 253, 255);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\Windows\\PycharmProjects\\ktlt-uel\\k25411\\ui\\../../../../.designer/images/ic_samplequantity.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonSampleQuantity.setIcon(icon5)
        self.pushButtonSampleQuantity.setIconSize(QtCore.QSize(30, 15))
        self.pushButtonSampleQuantity.setObjectName("pushButtonSampleQuantity")
        self.groupBox_8 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(800, 50, 191, 121))
        self.groupBox_8.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.groupBox_8.setAutoFillBackground(False)
        self.groupBox_8.setStyleSheet("font: 75 14pt \"Rockwell\";\n"
"background-color: rgb(207, 228, 255);\n"
"color: rgb(45, 5, 127);\n"
"border-radius: 20px;\n"
"padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);")
        self.groupBox_8.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.groupBox_8.setFlat(False)
        self.groupBox_8.setCheckable(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButtonOpenChartFeedback_4 = QtWidgets.QPushButton(parent=self.groupBox_8)
        self.pushButtonOpenChartFeedback_4.setGeometry(QtCore.QRect(40, 78, 111, 31))
        self.pushButtonOpenChartFeedback_4.setStyleSheet("background-color: rgb(67, 139, 196);\n"
"color: rgb(224, 253, 255);\n"
"\n"
"    border-radius: 10px;\n"
"    padding: 2px 8px;\n"
"border: 2px solid rgb(170,210,250);\n"
"font: 14pt \"Rockwell Condensed\";\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\Windows\\PycharmProjects\\ktlt-uel\\k25411\\ui\\../../../../.designer/images/ic_revenue.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOpenChartFeedback_4.setIcon(icon6)
        self.pushButtonOpenChartFeedback_4.setIconSize(QtCore.QSize(40, 25))
        self.pushButtonOpenChartFeedback_4.setObjectName("pushButtonOpenChartFeedback_4")
        self.pushButtonCloseWindow = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCloseWindow.setGeometry(QtCore.QRect(1000, 130, 151, 41))
        self.pushButtonCloseWindow.setStyleSheet("QPushButton{\n"
"    background-color: rgb(72,134,180);\n"
"    color: white;\n"
"\n"
"    border: 2px solid rgb(170,210,250);\n"
"    border-radius: 12px;\n"
"\n"
"    padding: 3px 12px;\n"
"    font: 75 12pt \"Rockwell\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(90,150,200);\n"
"    border: 2px solid rgb(190,220,255);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(60,120,170);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\Windows\\PycharmProjects\\ktlt-uel\\k25411\\ui\\../../../../.designer/images/ic_closewindow.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonCloseWindow.setIcon(icon7)
        self.pushButtonCloseWindow.setIconSize(QtCore.QSize(40, 15))
        self.pushButtonCloseWindow.setObjectName("pushButtonCloseWindow")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1195, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButtonCustomerClear.clicked.connect(self.lineEditType.clear) # type: ignore
        self.pushButtonSampleClear.clicked.connect(self.lineEditSampleName.clear) # type: ignore
        self.pushButtonSampleClear.clicked.connect(self.lineEditSampleID.clear) # type: ignore
        self.pushButtonSampleClear.clicked.connect(self.lineEditSampleQuantity.clear) # type: ignore
        self.pushButtonSampleClear.clicked.connect(self.lineEditPrice.clear) # type: ignore
        self.pushButtonSampleClear.clicked.connect(self.lineEditSampleID.setFocus) # type: ignore
        self.pushButtonCustomerClear.clicked.connect(self.lineEditCustomerUserName.clear) # type: ignore
        self.pushButtonCustomerClear.clicked.connect(self.lineEditPhoneNumber.clear) # type: ignore
        self.pushButtonCustomerClear.clicked.connect(self.lineEditCustomerUserName.setFocus) # type: ignore
        self.pushButtonEmployeeClear.clicked.connect(self.lineEditEmployeeID.clear) # type: ignore
        self.pushButtonEmployeeClear.clicked.connect(self.lineEditEmployeeName.clear) # type: ignore
        self.pushButtonEmployeeClear.clicked.connect(self.lineEditExperience.clear) # type: ignore
        self.pushButtonEmployeeClear.clicked.connect(self.lineEditCustomerBooked.clear) # type: ignore
        self.pushButtonEmployeeClear.clicked.connect(self.lineEditEmployeeID.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\"><br/></span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt; font-weight:600; color:#142d5a;\">Product Management</span></p></body></html>"))
        item = self.tableWidgetSample.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetSample.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetSample.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetSample.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidgetSample.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidgetSample.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidgetSample.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidgetSample.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableWidgetSample.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableWidgetSample.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10"))
        item = self.tableWidgetSample.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sample Name"))
        item = self.tableWidgetSample.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sample ID"))
        item = self.tableWidgetSample.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Sample Price"))
        item = self.tableWidgetSample.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sample Quantity"))
        __sortingEnabled = self.tableWidgetSample.isSortingEnabled()
        self.tableWidgetSample.setSortingEnabled(False)
        self.tableWidgetSample.setSortingEnabled(__sortingEnabled)
        self.groupBox.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">Sample Detail:</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Sample Detail:"))
        self.label_2.setText(_translate("MainWindow", "Sample ID:"))
        self.label_3.setText(_translate("MainWindow", "Sample Name:"))
        self.label_4.setText(_translate("MainWindow", "Price:"))
        self.pushButtonSampleSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonSampleClear.setText(_translate("MainWindow", "Clear"))
        self.pushButtonSampleSearch.setText(_translate("MainWindow", "Search"))
        self.pushButtonSampleRemove.setText(_translate("MainWindow", "Remove"))
        self.label_12.setText(_translate("MainWindow", "Sample Quantity:"))
        self.groupBox_2.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Sample Detail:</span></p></body></html>"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Customer Detail:"))
        self.label_5.setText(_translate("MainWindow", "Customer User Name:"))
        self.label_6.setText(_translate("MainWindow", "Phone Number:"))
        self.label_7.setText(_translate("MainWindow", "Type:"))
        self.pushButtonCustomerSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonCustomerClear.setText(_translate("MainWindow", "Clear"))
        self.pushButtonCustomerSearch.setText(_translate("MainWindow", "Search"))
        self.pushButtonCustomerRemove.setText(_translate("MainWindow", "Remove"))
        self.dateEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\"><br/></span></p></body></html>"))
        self.dateEdit.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.groupBox_5.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">Sample Detail:</p></body></html>"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Customer Feedback"))
        self.pushButtonOpenChartFeedback.setText(_translate("MainWindow", "Open Chart"))
        item = self.tableWidgetCustomer.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetCustomer.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetCustomer.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetCustomer.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidgetCustomer.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "User Name"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Phone Number"))
        item = self.tableWidgetCustomer.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type"))
        item = self.tableWidgetEmployee.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidgetEmployee.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidgetEmployee.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidgetEmployee.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidgetEmployee.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidgetEmployee.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Employee ID"))
        item = self.tableWidgetEmployee.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Employee Name"))
        item = self.tableWidgetEmployee.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Experience "))
        item = self.tableWidgetEmployee.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Customer Booked"))
        self.groupBox_6.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Sample Detail:</span></p></body></html>"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Employee Detail:"))
        self.label_8.setText(_translate("MainWindow", "Employee ID:"))
        self.label_9.setText(_translate("MainWindow", "Employee Name:"))
        self.label_10.setText(_translate("MainWindow", "Experience"))
        self.pushButtonEmployeeSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonEmployeeClear.setText(_translate("MainWindow", "Clear"))
        self.pushButtonEmployeeSearch.setText(_translate("MainWindow", "Search"))
        self.pushButtonEmployeeRemove.setText(_translate("MainWindow", "Remove"))
        self.label_11.setText(_translate("MainWindow", "Customer Booked:"))
        self.groupBox_7.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">Sample Detail:</p></body></html>"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Sample Quantity"))
        self.pushButtonSampleQuantity.setText(_translate("MainWindow", "Open Chart"))
        self.groupBox_8.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\">Sample Detail:</p></body></html>"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Revenue"))
        self.pushButtonOpenChartFeedback_4.setText(_translate("MainWindow", "Open Chart"))
        self.pushButtonCloseWindow.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Close Window</span></p></body></html>"))
        self.pushButtonCloseWindow.setText(_translate("MainWindow", "Close Window"))
