# Form implementation generated from reading ui file 'D:\Code\ktlt-uel\ui\SelfCustomWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelfCustomWindow(object):
    def setupUi(self, SelfCustomWindow):
        SelfCustomWindow.setObjectName("SelfCustomWindow")
        SelfCustomWindow.resize(1143, 936)
        SelfCustomWindow.setStyleSheet("/* Ép màu cho centralwidget và tất cả các con bên trong */\n"
"#centralwidget {\n"
"    background-color: #FFFFFF; /* Nền trắng */\n"
"    color: #000000;            /* Chữ đen */\n"
"}\n"
"\n"
"/* Đảm bảo các Label không bị Theme hệ thống ghi đè màu trắng */\n"
"QLabel {\n"
"    color: #000000;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=SelfCustomWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 70))
        self.label.setStyleSheet("color: white;\n"
"font-size: 14px;\n"
"background-color:#AFCBF3;\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setObjectName("widget")
        self.label_111 = QtWidgets.QLabel(parent=self.widget)
        self.label_111.setGeometry(QtCore.QRect(150, 0, 261, 281))
        self.label_111.setStyleSheet("border-radius: 20px; /* Bo tròn góc */\n"
"border: 2px solid #ccc; /* Viền màu xám */\n"
"background-color: white; /* Nền trắng */\n"
"")
        self.label_111.setText("")
        self.label_111.setObjectName("label_111")
        self.imagecoffee_43 = QtWidgets.QLabel(parent=self.widget)
        self.imagecoffee_43.setGeometry(QtCore.QRect(170, 20, 221, 231))
        self.imagecoffee_43.setText("")
        self.imagecoffee_43.setPixmap(QtGui.QPixmap("D:\\Code\\ktlt-uel\\ui\\../ima/plus.png"))
        self.imagecoffee_43.setScaledContents(True)
        self.imagecoffee_43.setObjectName("imagecoffee_43")
        self.buychocolatebalance_44 = QtWidgets.QPushButton(parent=self.widget)
        self.buychocolatebalance_44.setGeometry(QtCore.QRect(190, 300, 151, 41))
        self.buychocolatebalance_44.setStyleSheet("QPushButton {\n"
"    background-color:#AFCBF3; /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: #4A90E2; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid #A6C8FF; /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\Code\\ktlt-uel\\ui\\../ima/add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.buychocolatebalance_44.setIcon(icon)
        self.buychocolatebalance_44.setObjectName("buychocolatebalance_44")
        self.horizontalLayout.addWidget(self.widget)
        self.widget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 400))
        self.widget_4.setObjectName("widget_4")
        self.labelTitle = QtWidgets.QLabel(parent=self.widget_4)
        self.labelTitle.setGeometry(QtCore.QRect(30, 20, 259, 27))
        self.labelTitle.setStyleSheet("font-size: 22px; font-weight: bold; color: #4A90E2;")
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.paletteFrame = QtWidgets.QFrame(parent=self.widget_4)
        self.paletteFrame.setGeometry(QtCore.QRect(50, 60, 212, 212))
        self.paletteFrame.setObjectName("paletteFrame")
        self.gridLayoutColors = QtWidgets.QGridLayout(self.paletteFrame)
        self.gridLayoutColors.setSpacing(10)
        self.gridLayoutColors.setObjectName("gridLayoutColors")
        self.color_16 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_16.setMinimumSize(QtCore.QSize(30, 30))
        self.color_16.setMaximumSize(QtCore.QSize(30, 30))
        self.color_16.setObjectName("color_16")
        self.gridLayoutColors.addWidget(self.color_16, 3, 0, 1, 1)
        self.color_17 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_17.setMinimumSize(QtCore.QSize(30, 30))
        self.color_17.setMaximumSize(QtCore.QSize(30, 30))
        self.color_17.setObjectName("color_17")
        self.gridLayoutColors.addWidget(self.color_17, 3, 1, 1, 1)
        self.color_5 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_5.setMinimumSize(QtCore.QSize(30, 30))
        self.color_5.setMaximumSize(QtCore.QSize(30, 30))
        self.color_5.setObjectName("color_5")
        self.gridLayoutColors.addWidget(self.color_5, 0, 4, 1, 1)
        self.color_7 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_7.setMinimumSize(QtCore.QSize(30, 30))
        self.color_7.setMaximumSize(QtCore.QSize(30, 30))
        self.color_7.setObjectName("color_7")
        self.gridLayoutColors.addWidget(self.color_7, 1, 1, 1, 1)
        self.color_4 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_4.setMinimumSize(QtCore.QSize(30, 30))
        self.color_4.setMaximumSize(QtCore.QSize(30, 30))
        self.color_4.setObjectName("color_4")
        self.gridLayoutColors.addWidget(self.color_4, 0, 3, 1, 1)
        self.color_3 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_3.setMinimumSize(QtCore.QSize(30, 30))
        self.color_3.setMaximumSize(QtCore.QSize(30, 30))
        self.color_3.setObjectName("color_3")
        self.gridLayoutColors.addWidget(self.color_3, 0, 2, 1, 1)
        self.color_6 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_6.setMinimumSize(QtCore.QSize(30, 30))
        self.color_6.setMaximumSize(QtCore.QSize(30, 30))
        self.color_6.setObjectName("color_6")
        self.gridLayoutColors.addWidget(self.color_6, 1, 0, 1, 1)
        self.color_8 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_8.setMinimumSize(QtCore.QSize(30, 30))
        self.color_8.setMaximumSize(QtCore.QSize(30, 30))
        self.color_8.setObjectName("color_8")
        self.gridLayoutColors.addWidget(self.color_8, 1, 2, 1, 1)
        self.color_9 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_9.setMinimumSize(QtCore.QSize(30, 30))
        self.color_9.setMaximumSize(QtCore.QSize(30, 30))
        self.color_9.setObjectName("color_9")
        self.gridLayoutColors.addWidget(self.color_9, 1, 3, 1, 1)
        self.color_11 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_11.setMinimumSize(QtCore.QSize(30, 30))
        self.color_11.setMaximumSize(QtCore.QSize(30, 30))
        self.color_11.setObjectName("color_11")
        self.gridLayoutColors.addWidget(self.color_11, 2, 0, 1, 1)
        self.color_12 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_12.setMinimumSize(QtCore.QSize(30, 30))
        self.color_12.setMaximumSize(QtCore.QSize(30, 30))
        self.color_12.setObjectName("color_12")
        self.gridLayoutColors.addWidget(self.color_12, 2, 1, 1, 1)
        self.color_19 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_19.setMinimumSize(QtCore.QSize(30, 30))
        self.color_19.setMaximumSize(QtCore.QSize(30, 30))
        self.color_19.setObjectName("color_19")
        self.gridLayoutColors.addWidget(self.color_19, 3, 3, 1, 1)
        self.color_22 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_22.setMinimumSize(QtCore.QSize(30, 30))
        self.color_22.setMaximumSize(QtCore.QSize(30, 30))
        self.color_22.setObjectName("color_22")
        self.gridLayoutColors.addWidget(self.color_22, 4, 1, 1, 1)
        self.color_21 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_21.setMinimumSize(QtCore.QSize(30, 30))
        self.color_21.setMaximumSize(QtCore.QSize(30, 30))
        self.color_21.setObjectName("color_21")
        self.gridLayoutColors.addWidget(self.color_21, 4, 0, 1, 1)
        self.color_20 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_20.setMinimumSize(QtCore.QSize(30, 30))
        self.color_20.setMaximumSize(QtCore.QSize(30, 30))
        self.color_20.setObjectName("color_20")
        self.gridLayoutColors.addWidget(self.color_20, 3, 4, 1, 1)
        self.color_25 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_25.setMinimumSize(QtCore.QSize(30, 30))
        self.color_25.setMaximumSize(QtCore.QSize(30, 30))
        self.color_25.setObjectName("color_25")
        self.gridLayoutColors.addWidget(self.color_25, 4, 4, 1, 1)
        self.color_23 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_23.setMinimumSize(QtCore.QSize(30, 30))
        self.color_23.setMaximumSize(QtCore.QSize(30, 30))
        self.color_23.setObjectName("color_23")
        self.gridLayoutColors.addWidget(self.color_23, 4, 2, 1, 1)
        self.color_24 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_24.setMinimumSize(QtCore.QSize(30, 30))
        self.color_24.setMaximumSize(QtCore.QSize(30, 30))
        self.color_24.setObjectName("color_24")
        self.gridLayoutColors.addWidget(self.color_24, 4, 3, 1, 1)
        self.color_1 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_1.setMinimumSize(QtCore.QSize(30, 30))
        self.color_1.setMaximumSize(QtCore.QSize(30, 30))
        self.color_1.setObjectName("color_1")
        self.gridLayoutColors.addWidget(self.color_1, 0, 0, 1, 1)
        self.color_2 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_2.setMinimumSize(QtCore.QSize(30, 30))
        self.color_2.setMaximumSize(QtCore.QSize(30, 30))
        self.color_2.setObjectName("color_2")
        self.gridLayoutColors.addWidget(self.color_2, 0, 1, 1, 1)
        self.color_14 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_14.setMinimumSize(QtCore.QSize(30, 30))
        self.color_14.setMaximumSize(QtCore.QSize(30, 30))
        self.color_14.setObjectName("color_14")
        self.gridLayoutColors.addWidget(self.color_14, 2, 3, 1, 1)
        self.color_13 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_13.setMinimumSize(QtCore.QSize(30, 30))
        self.color_13.setMaximumSize(QtCore.QSize(30, 30))
        self.color_13.setObjectName("color_13")
        self.gridLayoutColors.addWidget(self.color_13, 2, 2, 1, 1)
        self.color_18 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_18.setMinimumSize(QtCore.QSize(30, 30))
        self.color_18.setMaximumSize(QtCore.QSize(30, 30))
        self.color_18.setObjectName("color_18")
        self.gridLayoutColors.addWidget(self.color_18, 3, 2, 1, 1)
        self.color_10 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_10.setMinimumSize(QtCore.QSize(30, 30))
        self.color_10.setMaximumSize(QtCore.QSize(30, 30))
        self.color_10.setObjectName("color_10")
        self.gridLayoutColors.addWidget(self.color_10, 1, 4, 1, 1)
        self.color_15 = QtWidgets.QPushButton(parent=self.paletteFrame)
        self.color_15.setMinimumSize(QtCore.QSize(30, 30))
        self.color_15.setMaximumSize(QtCore.QSize(30, 30))
        self.color_15.setObjectName("color_15")
        self.gridLayoutColors.addWidget(self.color_15, 2, 4, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(parent=self.widget_4)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 290, 291, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setVerticalSpacing(20)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setStyleSheet("font-weight: bold; color: rgb(15, 15, 15);")
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.txtSelectedColor = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txtSelectedColor.setStyleSheet("border: 1px solid #AFCBF3; padding: 10px; color: rgb(15, 15, 15); border-radius: 5px; background-color:#AFCBF3;")
        self.txtSelectedColor.setReadOnly(True)
        self.txtSelectedColor.setObjectName("txtSelectedColor")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtSelectedColor)
        self.buychocolatebalance_45 = QtWidgets.QPushButton(parent=self.widget_4)
        self.buychocolatebalance_45.setGeometry(QtCore.QRect(30, 340, 251, 41))
        self.buychocolatebalance_45.setStyleSheet("QPushButton {\n"
"    background-color:#AFCBF3; /* Màu xanh nhạt chủ đạo bạn chọn */\n"
"    color: #4A90E2; /* Chữ màu xanh đậm để dễ đọc trên nền nhạt */\n"
"    border-radius: 12px;\n"
"    padding: 10px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    font-family: \"Georgia\";\n"
"    border: 2px solid #A6C8FF; /* Viền xanh đậm hơn một chút để tạo khối */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #A6C8FF; /* Màu đậm hơn khi di chuột vào */\n"
"    border: 2px solid #7FAFFF; /* Viền đậm hơn khi hover */\n"
"    color: white; /* Chuyển chữ sang trắng để nổi bật */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #7FAFFF; /* Màu đậm nhất khi nhấn giữ nút */\n"
"    border: 2px solid #4A90E2;\n"
"}")
        self.buychocolatebalance_45.setObjectName("buychocolatebalance_45")
        self.horizontalLayout.addWidget(self.widget_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.widget_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 241, 41))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.chooseTheStyleLabel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.chooseTheStyleLabel.setObjectName("chooseTheStyleLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.chooseTheStyleLabel)
        self.chooseTheStyleComboBox = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.chooseTheStyleComboBox.setStyleSheet(" background-color:#AFCBF3; color: rgb(15, 15, 15);")
        self.chooseTheStyleComboBox.setObjectName("chooseTheStyleComboBox")
        self.chooseTheStyleComboBox.addItem("")
        self.chooseTheStyleComboBox.addItem("")
        self.chooseTheStyleComboBox.addItem("")
        self.chooseTheStyleComboBox.addItem("")
        self.chooseTheStyleComboBox.addItem("")
        self.chooseTheStyleComboBox.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chooseTheStyleComboBox)
        self.formLayoutWidget_2 = QtWidgets.QWidget(parent=self.widget_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(280, 0, 241, 41))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.chooseTheStyleLabel_2 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.chooseTheStyleLabel_2.setObjectName("chooseTheStyleLabel_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.chooseTheStyleLabel_2)
        self.chooseTheStyleComboBox_2 = QtWidgets.QComboBox(parent=self.formLayoutWidget_2)
        self.chooseTheStyleComboBox_2.setStyleSheet(" background-color:#AFCBF3; color: rgb(15, 15, 15);")
        self.chooseTheStyleComboBox_2.setObjectName("chooseTheStyleComboBox_2")
        self.chooseTheStyleComboBox_2.addItem("")
        self.chooseTheStyleComboBox_2.addItem("")
        self.chooseTheStyleComboBox_2.addItem("")
        self.chooseTheStyleComboBox_2.addItem("")
        self.chooseTheStyleComboBox_2.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.chooseTheStyleComboBox_2)
        self.verticalLayout.addWidget(self.widget_2)
        SelfCustomWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=SelfCustomWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1143, 18))
        self.menubar.setObjectName("menubar")
        SelfCustomWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=SelfCustomWindow)
        self.statusbar.setObjectName("statusbar")
        SelfCustomWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SelfCustomWindow)
        QtCore.QMetaObject.connectSlotsByName(SelfCustomWindow)

    def retranslateUi(self, SelfCustomWindow):
        _translate = QtCore.QCoreApplication.translate
        SelfCustomWindow.setWindowTitle(_translate("SelfCustomWindow", "MainWindow"))
        self.label.setText(_translate("SelfCustomWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">CUSTOM YOUR DESIGN</span></p></body></html>"))
        self.buychocolatebalance_44.setText(_translate("SelfCustomWindow", "Photo Upload"))
        self.labelTitle.setText(_translate("SelfCustomWindow", "SELECT YOUR SHADE"))
        self.color_16.setStyleSheet(_translate("SelfCustomWindow", "background-color: #800080; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_17.setStyleSheet(_translate("SelfCustomWindow", "background-color: #E6E6FA; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_5.setStyleSheet(_translate("SelfCustomWindow", "background-color: #800000; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_7.setStyleSheet(_translate("SelfCustomWindow", "background-color: #FFFF00; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_4.setStyleSheet(_translate("SelfCustomWindow", "background-color: #DB7093; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_3.setStyleSheet(_translate("SelfCustomWindow", "background-color: #FFC0CB; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_6.setStyleSheet(_translate("SelfCustomWindow", "background-color: #FFA500; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_8.setStyleSheet(_translate("SelfCustomWindow", "background-color: #FFD700; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_9.setStyleSheet(_translate("SelfCustomWindow", "background-color: #F4A460; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_11.setStyleSheet(_translate("SelfCustomWindow", "background-color: #008000; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_12.setStyleSheet(_translate("SelfCustomWindow", "background-color: #90EE90; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_19.setStyleSheet(_translate("SelfCustomWindow", "background-color: #D2B48C; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_22.setStyleSheet(_translate("SelfCustomWindow", "background-color: #FFFFFF; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_21.setStyleSheet(_translate("SelfCustomWindow", "background-color: #000000; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_20.setStyleSheet(_translate("SelfCustomWindow", "background-color: #F5F5DC; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_25.setStyleSheet(_translate("SelfCustomWindow", "background-color: #708090; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_23.setStyleSheet(_translate("SelfCustomWindow", "background-color: #808080; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_24.setStyleSheet(_translate("SelfCustomWindow", "background-color: #C0C0C0; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_1.setStyleSheet(_translate("SelfCustomWindow", "background-color: #FF0000; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_2.setStyleSheet(_translate("SelfCustomWindow", "background-color: #FF1493; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_14.setStyleSheet(_translate("SelfCustomWindow", "background-color: #ADD8E6; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_13.setStyleSheet(_translate("SelfCustomWindow", "background-color: #0000FF; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_18.setStyleSheet(_translate("SelfCustomWindow", "background-color: #A52A2A; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_10.setStyleSheet(_translate("SelfCustomWindow", "background-color: #E9967A; border-radius: 15px; border: 1px solid #ddd;"))
        self.color_15.setStyleSheet(_translate("SelfCustomWindow", "background-color: #000080; border-radius: 15px; border: 1px solid #ddd;"))
        self.label_3.setText(_translate("SelfCustomWindow", "Color Selection:"))
        self.txtSelectedColor.setPlaceholderText(_translate("SelfCustomWindow", "Touch a shade above..."))
        self.buychocolatebalance_45.setText(_translate("SelfCustomWindow", "CONFIRM COLOR CHOICE"))
        self.chooseTheStyleLabel.setText(_translate("SelfCustomWindow", "Choose the style:"))
        self.chooseTheStyleComboBox.setItemText(0, _translate("SelfCustomWindow", "..........."))
        self.chooseTheStyleComboBox.setItemText(1, _translate("SelfCustomWindow", "Square"))
        self.chooseTheStyleComboBox.setItemText(2, _translate("SelfCustomWindow", "Round"))
        self.chooseTheStyleComboBox.setItemText(3, _translate("SelfCustomWindow", "Oval"))
        self.chooseTheStyleComboBox.setItemText(4, _translate("SelfCustomWindow", "Almond"))
        self.chooseTheStyleComboBox.setItemText(5, _translate("SelfCustomWindow", "Stiletto"))
        self.chooseTheStyleLabel_2.setText(_translate("SelfCustomWindow", "Select long length:"))
        self.chooseTheStyleComboBox_2.setItemText(0, _translate("SelfCustomWindow", "............."))
        self.chooseTheStyleComboBox_2.setItemText(1, _translate("SelfCustomWindow", "Short"))
        self.chooseTheStyleComboBox_2.setItemText(2, _translate("SelfCustomWindow", "Medium"))
        self.chooseTheStyleComboBox_2.setItemText(3, _translate("SelfCustomWindow", "Long"))
        self.chooseTheStyleComboBox_2.setItemText(4, _translate("SelfCustomWindow", "Extra Long"))
